server:
    name: "awesomeProject"
    version: "awesomeProject"
    host: "0.0.0.0"
    port: 8083
    mode: "live"
    path: "live"
    exec_path: "live"
    url: "http://localhost:8080"
    key: "tN3XSDHWF8ZPOERtQRnkVMZYHgghteT7"
    env: "dev"
    currency: "USD"
    debug: true

view:
    path: "web/views/app"
    extension: ".html"
    assets_path: "web/dist"

migration:
    dir: "migrations"
    table: "migrations"



database:
    driver: "postgres"
    host: "localhost"
    username: "postgres"
    password: "root"
    db_name: "test"
    port: 5432
    connections: 100
    idle_connections: 80

cache:
    driver: "redis"
    name: "redis-cache"
    password:
    host: "localhost"
    port: 6379
    db: ""
